const clients = {
  'mahnaz-arianmanesh': {
    logo: 'مهناز آریان منش',
    founder: 'مهناز آریان منش',
    phone: '09134281455',
    clinicName: 'کلینیک آریان منش',
    quote: 'مهناز آریان منش، روانشناس بالینی',
    founderImg:
      'https://mahnazarianmanesh.ir/uploadfile/file_portal/site_14305_web/file_portal_end/%D9%BE%DB%8C%D9%88%D9%86%D8%AF-%D9%87%D8%A7%DB%8C-%D8%B3%D8%A7%DB%8C%D8%AA/%D8%A7%D8%B3%D9%84%D8%A7%DB%8C%D8%AF%D8%B1/12-5343824-%D8%B4%D9%81%D8%A7%D9%81.webp',
  },
  'aeen-clinic': {
    logo: 'مرکز مشاوره آیین',
    founder: 'محمد کربلایی',
    phone: '09130500368',
    clinicName: 'مرکز مشاوره آیین',
    quote: 'محمد کربلایی، زوج درمانگر و بنیان گذار مرکز مشاوره آیین',
    founderImg: 'https://aeencc.com/wp-content/uploads/2025/04/mohammad-karbalaii-3.webp',
  },
  'tohid-clinic': {
    logo: 'مرکز مشاوره توحید',
    founder: 'بنیان گذار مرکز مشاوره توحید',
    phone: '09138389020',
    clinicName: 'مرکز مشاوره توحید',
    quote: 'بنیان گذار مرکز مشاوره توحید',
  },
  'shaghayegh-bazargan': {
    logo: 'شقایق بازرگان',
    founder: 'دکتر شقایق بازرگان',
    phone: '09134625934',
    clinicName: 'کلینیک بازرگان',
    quote: 'شقایق بازرگان، روانشناس بالینی',
    founderImg: 'https://dbazargan.ir/wp-content/uploads/2022/09/BG-barzagan.jpg',
  },
  'azadi-clinic': {
    logo: 'مرکز مشاوره آزادی',
    founder: 'اعظم اعرابی',
    phone: '09394268643',
    clinicName: 'مرکز مشاوره آزادی',
    quote: 'بنیان گذار مرکز مشاوره آزادی',
  },
  'harekate-no': {
    logo: 'مرکز مشاوره حرکت نو',
    founder: 'اعظم اعرابی',
    phone: '09138368256',
    clinicName: 'مرکز مشاوره حرکت نو',
    quote: 'اعظم اعرابی، روانشناس بالینی و بنیان گذار مرکز مشاوره حرکت نو',
  },
  salam: {
    logo: 'مرکز مشاوره سلام',
    founder: 'بنیان گذار مرکز مشاوره سلام',
    phone: '09138100149',
    clinicName: 'مرکز مشاوره سلام',
    quote: 'بنیان گذار مرکز مشاوره سلام',
  },
  'janan-clinic': {
    logo: 'مرکز مشاوره جانان',
    founder: 'آوا لباف',
    phone: '09911182380',
    clinicName: 'مرکز مشاوره جانان',
    quote: 'آوا لباف، روان دروانگر و بنیان گذار مرکز مشاوره جانان',
    founderImg: 'https://jananclinic.ir/wp-content/uploads/2026/06/ava-labbaf-2.webp',
  },
  'dr-pouralizade': {
    logo: 'استاد پورعلی زاده',
    founder: 'استاد پور علی زاده',
    phone: '09134118416',
    clinicName: 'مرکز مشاوره پورعلی زاده',
    quote: 'استاد پورعلی زاده، مشاور و روانشناس',
    founderImg: 'https://pouralizade.ir/wp-content/uploads/2025/12/prifile-01-e1762507076546.webp',
  },
  'khorshid-clinic': {
    logo: 'مرکز مشاوره خورشید',
    founder: 'وحید سلطانیان',
    phone: '09137533407',
    clinicName: 'مرکز مشاوره خورشید',
    quote: 'وحید سلطانیان، روان دروانگر و بنیان گذار مرکز مشاوره خورشید',
  },
  'zeynab-afrasiyab': {
    logo: 'زینب افراسیاب',
    founder: 'زینب افراسیاب',
    phone: '09364582226',
    clinicName: 'کلینیک زینب افراسیاب',
    quote: 'زینب افراسیاب، روان درمانگر و مشاور خانواده',
  },
  'mehrnoosh-zabihi': {
    logo: 'مهرنوش ذبیحی',
    founder: 'مهرنوش ذبیحی',
    phone: '09900817302',
    clinicName: 'کلینیک مهرنوش ذبیحی',
    quote: 'مهرنوش ذبیحی، روانشناس فردی و تراپیست والدین',
    founderImg: 'https://mehrnooshzabihi.ir/wp-content/uploads/ehrnoosh-zabihi-3.jpg',
  },
  'nastaran-barahimi': {
    logo: 'نسترن براهیمی',
    founder: 'نسترن براهیمی',
    phone: '09397940041',
    clinicName: 'کلینیک براهیمی',
    quote: 'نسترن براهیمی، متخصص روابط بین فردی و روانشناس خانواده',
  },
  'bamdad-clinic': {
    logo: 'مرکز مشاوره بامداد',
    founder: 'حمید آتش پور',
    phone: '03136683860',
    clinicName: 'مرکز مشاوره بامداد',
    quote: 'حمید آتش پور، روان شناس و بنیان گذار مرکز مشاوره بامداد',
  },
  'darya-clinic': {
    logo: 'مرکز مشاوره دریا',
    founder: 'الناز صفری',
    phone: '03145244602',
    clinicName: 'مرکز مشاوره دریا',
    quote: 'الناز صفری، روان درمانگر و بنیان گذار مرکز مشاوره دریا',
  },
  'mehraein-clinic': {
    logo: 'کلینیک مهر آیین دانایی',
    founder: 'بنیان گذار مرکز مشاوره مهر آیین',
    phone: '09136400103',
    clinicName: 'کلینیک مهر آیین دانایی',
    quote: 'بنیان گذار مرکز مشاوره مهر آیین',
  },
  'sara-moghdam': {
    logo: 'سارا مقدم',
    founder: 'سارا عزیزی مقدم',
    phone: '۰۹۱۲۰۲۴۴۹۸۴',
    clinicName: 'کلینیک مقدم',
    quote: 'سارا مقدم، مشاور و روانشناس بالینی',
  },
  'mostafa-najmabadi': {
    logo: 'مصطفی نجم آبادی',
    founder: 'مصطفی نجم آبادی',
    phone: '09199889464',
    clinicName: 'کلینیک نجم آبادی',
    quote: 'مصطفی نجم آبادی، روانشناس و روان درمانگر متخصص EFT',
  },
  'nik-mind': {
    logo: 'کلینیک نیک مایند',
    founder: 'بنیان گذار کلینیک نیک مایند',
    phone: '۰۲۱۸۲۸۰۸۰۵۵',
    clinicName: 'کلینیک نیک مایند',
    quote: 'بنیان گذار کلینیک نیک مایند',
    heading: 'کلینیک روانشناسی نیک مایند',
    description:
      'کلینیک روانشناسی و روانپزشکی نیک مایند با بهره‌گیری از درمانگران مجرب با استفاده از رویکرد علمی و روش‌های درمانی مؤثر در همه‌ی زمینه های سلامت روان درصدد کمک و حل مشکلات مراجعین عزیز به صورت حضوری و آنلاین می‌باشد',
  },
  'noora-clinic': {
    logo: 'مرکز مشاوره نورا',
    founder: 'پریا پیرنیاکان',
    phone: '۰۹۰۵۰۱۷۹۰۹۶',
    clinicName: 'مرکز مشاوره روانشناسی نورا',
    quote: 'پریا پیرنیاکان، روانشناس بالینی',
    heading: 'کلینیک روانشناسی و مشاوره نورا',
  },
  'ehya-clinic': {
    logo: 'مرکز مشاوره احیا',
    founder: 'بنیان گذار مرکز مشاوره احیا',
    phone: '02191090873',
    clinicName: 'مرکز خدمات روانشناسی و مشاوره احیا',
    quote: 'بنیان گذار مرکز مشاوره احیا',
    heading: 'مرکز روانشناسی و مشاوره احیا',
  },
  'anahid-khatibzadeh': {
    logo: 'دکتر آناهید خطیب زاده',
    founder: 'آناهید خطیب زاده',
    phone: '02122004658',
    clinicName: 'کلینیک روانشناسی و مشاوره راهیل',
    quote: 'آناهید خطیب زاده، روانشناس و بنیان گذار کلینیک راهیل',
    heading: 'کلینیک روانشناسی و مشاوره راهیل',
  },
  'panah-clinic': {
    logo: 'مرکز مشاوره پناه',
    founder: 'بنیان گذار مرکز مشاوره پناه',
    phone: '09123456789',
    clinicName: 'کلینیک پناه',
    quote: 'بنیان گذار مرکز مشاوره پناه',
    heading: 'پلتفرم تخصصی سلامت روان پناه',
  },
  'setareh-iranian': {
    logo: 'کلینیک ستاره ایرانیان',
    founder: 'بنیان گذار کلینیک ستاره ایرانیان',
    phone: '۰۲۱۸۸۴۲۲۴۹۵',
    clinicName: 'کلینیک ستاره ایرانیان',
    quote: 'بنیان گذار کلینیک ستاره ایرانیان',
    heading: 'مرکز مشاوره ستاره ایرانیان',
  },
  'mehraein-therapy': {
    logo: 'کلینیک مهرآیین',
    founder: 'بنیان گذار کلینیک مهرآیین',
    phone: '۰۹۳۳۸۵۵۸۷۰۰',
    clinicName: 'مرکز مشاوره مهرآیین',
    quote: 'بنیان گذار کلینیک مهرآیین',
    heading: 'مرکز مشاوره تخصصی مهرآیین',
  },
  'nahid-alizadeh': {
    logo: 'کلینیک علیزاده',
    founder: 'ناهید علیزاده',
    phone: '۰۹۳۰۷۶۷۲۵۵۴',
    clinicName: 'کلینیک علیزاده',
    quote: 'ناهید علیزاده، روانشناس بالینی',
    heading: 'دکتر ناهید علیزاده',
  },
  'marzie-mozaf': {
    logo: 'مرضیه مضاف',
    founder: 'مرضیه مضاف',
    phone: '09123456789',
    clinicName: 'کلینیک مضاف',
    quote: 'مرضیه مضاف، روانشناس و طرحواره درمانگر',
    heading: 'مرضیه مضاف، مشاور و طرحواره درمانگر',
  },
  'sara-akbarzadeh': {
    logo: 'سارا اکبرزاده',
    founder: 'سارا اکبرزاده',
    phone: '۰۹۱۳۰۹۹۴۶۳۹',
    clinicName: 'کلینیک گمان',
    quote: 'سارا اکبرزاده، روانشناس و موسس کلینیک گمان',
    heading: 'سارا اکبرزاده، مشاور و درمانگر',
    imagePath: '/sara-akbarzadeh.webp',
  },
  'ali-mirsadeghi': {
    logo: 'علی میرصادقی',
    founder: 'علی میرصادقی',
    phone: '09123456789',
    clinicName: 'کلینیک میرصادقی',
    quote: 'علی میرصادقی، روانشناس و رواندرمانگر',
    heading: 'علی میرصادقی، مشاور و درمانگر',
    imagePath: '/ali-mirsadeghi.webp',
    imagePosition: '50%_30%',
  },
  'morteza-tavakoli': {
    logo: 'مرتضی توکلی',
    founder: 'مرتضی توکلی',
    phone: '۰۹۱۲۳۴۵۶۷۸۹',
    clinicName: 'کلینیک توکلی',
    quote: 'مرتضی توکلی، روانشناس و رواندرمانگر',
    heading: 'مرتضی توکلی، مشاور و درمانگر',
    imagePath: '/morteza-tevakoli.webp',
    imagePosition: 'center',
  },
  'nazgol-khalili': {
    logo: 'نازگل خلیلی',
    founder: 'نازگل خلیلی',
    phone: '۰۹۹۱۷۳۴۵۱۴۴',
    clinicName: 'کلینیک ارگال',
    quote: 'نازگل خلیلی، روانشناس و رواندرمانگر',
    heading: 'نازگل خلیلی، روانشناس و درمانگر',
    imagePath: '/nazgol-khalili.webp',
  },
  'morteza-jodat': {
    logo: 'مرتضی جودت',
    founder: 'مرتضی جودت',
    phone: '۰۹۳۰۳۰۱۱۳۱۸',
    clinicName: 'کلینیک جودت',
    heading: 'مرتضی جودت، روانشناس و درمانگر',
    imagePath: '/morteza-jodat.webp',
    imagePosition: 'center',
  },
  'sara-larjani': {
    logo: 'سارا لارجانی',
    founder: 'سارا لارجانی',
    phone: '۰۹۳۹۰۰۷۷۲۲۹',
    clinicName: 'کلینیک لارجانی',
    heading: 'سارا لارجانی، روانشناس و درمانگر',
  },
  'aida-haghi': {
    logo: 'آیدا حقی',
    founder: 'آیدا حقی',
    phone: '۰۹۳۳۶۰۵۵۲۳۶',
    clinicName: 'کلینیک حقی',
    quote: 'آیدا حقی، روانشناس و زوج درمانگر',
    heading: 'آیدا حقی، روانشناس و درمانگر',
    imagePath: '/aida-haghi.webp',
  },
  'zahra-karami': {
    logo: 'زهرا کرمی',
    founder: 'زهرا کرمی',
    phone: '09224027921',
    clinicName: 'کلینیک کرمی',
    quote: 'زهرا کرمی، روانشناس و رواندرمانگر',
    heading: 'زهرا کرمی، مشاور و درمانگر',
    imagePath: '/zahra-karami.webp',
  },
  'mohammadali-shk': {
    logo: 'محمدعلی اشکش',
    founder: 'محمدعلی اشکش',
    phone: '09383519361',
    clinicName: "کلینیک اشکش",
    quote : "محمدعلی اشکش، روانشناس بالینی",
    heading : "محمدعلی اشکش، مشاور و درمانگر"
  },
};

export default clients;
